cargo-features = ["strip"]

[package]
name = "rsx"
version = "0.1.0"
authors = ["Vladislav Mamon <norskeld@gmail.com>"]
description = "Micro CLI to interactively run npm & yarn scripts."
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"

[profile.release]
lto = true
opt-level = "s"
strip = "symbols"
